version: '2'
services:
    jhipstersampleapplicationproject-app:
        image: jhipstersampleapplicationproject
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://jhipstersampleapplicationproject-postgresql:5432/jhipsterSampleApplicationProject
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=jhipstersampleapplicationproject-elasticsearch:9300
        ports:
            - 8080:8080
    jhipstersampleapplicationproject-postgresql:
        extends:
            file: postgresql.yml
            service: jhipstersampleapplicationproject-postgresql
    jhipstersampleapplicationproject-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: jhipstersampleapplicationproject-elasticsearch
