version: '2'
services:
    jhipstersampleapplicationproject-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/jhipsterSampleApplicationProject/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=jhipsterSampleApplicationProject
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
